ghost:
  image: ghost:1.19.0
  container_name: bacapesat_blog
  volumes: 
    - /opt/ghost_blog:/var/lib/ghost/content
  environment:
    - url=https://bacapesat.com
    - VIRTUAL_HOST=bacapesat.com
    - LETSENCRYPT_HOST=bacapesat.com
    - LETSENCRYPT_EMAIL=hieronymilanisti09@gmail.com
  restart: always
